language: node_js
node_js: stable
sudo: required
addons:
  chrome: stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        MssZ1ZQYbb6gSdrpLViJAT1Go16kfkGWKTpCXuAT/gXuLYZCu3XTf3FY0n7BUAaakxGZpQy24OlH0x2jdZ08lB7g8pAEx8v5sFD5nHoOW8mdHHADhHwP9RHj2c+9X/3me0EIkGboHjas2GbrkyOb7iFMrE2qbMf+N7hNHlV+dHO4FUrRXhkegPDx3ptdx0zeXOrYTGqRGv6gYy3shQRPxGCPmnauEsfs7yOFLcluqisTTsRgYwNmCP9fTEhpESHhDW5PvXUSrM+cTO3DEZXCbG1cr+vUZG5L0RepPIw+/gM9KvzaRvjSVBevUx1xdfKGMCPM/W6515oGU0IVRSfhZL8SA7rDBze4N9HxSP2/gecCTIska5uMm4MNZXM6GMD8Osl9i/mh1Y1TYit1BtNTpwCr6UiDdhjKasmhmTlUNDxx1lasEpM9krY8tyf/tlthx0KzyYo8WdLJcST/nl48xHKGTwW1czzHinAmygpyOv0dBoQKb544seFLO7f4uxFyXHPWxVKCsX7XsGMlBvQEUv22YcsxJbdae6UiAg1x/Sem4vTwSohYHJq0DErG+EIP7TB1oZfwnMZWHsBVrRvYcW40g7wtUqR78Ej/+QxMsKhzcQBK6XDBFc1N9WwbNfuGl+S6mG/Q3uEItqwWrfwo0HY/fD6mJyN9kgp+WLldtbg=
    - secure: >-
        R6TKWQmBBJ3DtZiErr8c5bWH6jfYmVCaoQqRRJz8ZZYnDQZBtY7fQmpUtdiiiGQfm6Wjcl3Qcusu7O+7CMsMyl9SYhI3+aFZmhYIsbCTz4AfZAt9rLGExHWDop2tSGfFU+KSgENl1LR20TM9s81rRQzrwg5sMAmgO4yLGCH9QKwT5lG2Oe4tl1FMYsjBc/lJbtJOm/c1pJVQXMoanrFVvkRlYgYG157xas5e33vaxmDPltS0WkoHp0T98Tyn30UW7waQhjUKtJ1PoDcyuVi1ugyGXGNLRfyqWUoypySJgVRI0U43WzcOz3G4WhuM0/JiQsSiNCm0eQW5azr61O20AuGaIxYy33CBBdUKpHPunmIJVwOydZ4RNkI1pvHTryi7GjSpXhjNCb1297bVL8Nv+6EG29AdsAGYpHZnptim+XQAqGJ/3ZXVZiIyF2u8iSPKYvhcuE8y+6lCPw+gOsMqIIBL8cvhjHhWSswl7jRnhR+S3rxcclEM8cg4rtO2uDcKpL0WRUa1l+G71Kw3EtL7ZI1hl+6HQQxQlPy0bKlJvI6ThmlDYVwAYkmIYN4G/QhJnoNJwTtpAJw/I4SjAL2hlegv7tv/rt5BsrBYVnOvw/0BZUjD2OJl0O+H98FiP8A4smjUrs/DmL7pxqSuCnI0xUMha6bniXLqfhLLhwvnZaU=
